/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f8fafc',
        surface: '#ffffff',
        'surface-dim': '#f1f5f9',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5f9',
        'surface-container': '#f8fafc',
        'surface-container-high': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'inverse-surface': '#0f172a',
        'inverse-on-surface': '#f8fafc',
        outline: '#94a3b8',
        'outline-variant': '#cbd5e1',
        primary: '#005ac2',
        'on-primary': '#ffffff',
        'primary-container': '#d8e2ff',
        'on-primary-container': '#001a42',
        secondary: '#006a60',
        'on-secondary': '#ffffff',
        'secondary-container': '#71f8e4',
        'on-secondary-container': '#00201c',
        tertiary: '#5b5e66',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#410002',
        'secondary-fixed': '#006a60',
        'secondary-fixed-dim': '#006a60',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Geist', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
